version: 0.1

phases:
  install:
    commands:
      - echo Installing Node.js and Yarn...
      - apt-get update
      - apt-get install -y nodejs
      - apt-get install -y yarn 

  pre_build:
    commands:
      - echo installing dependencies...
      - npm install -g @angular/cli@15.2.4

  build:
    commands:
      - cd Glasstop-brand-monitoring
      - npm i
      - ng build --prod

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/Glasstop-brand-monitoring
